language: objective-c
osx_image: xcode7.1
script:
- xcodebuild clean build -workspace Examples/SKAsyncGLViewController/SKAsyncGLViewController.xcworkspace -scheme SKAsyncGLViewController -sdk iphonesimulator9.3
