language: objective-c
osx_image: xcode7.1
sudo: false

script:
- cd Examples/SKAsyncGLViewController
- xcodebuild clean build -workspace SKAsyncGLViewController.xcworkspace -scheme SKAsyncGLViewController -sdk iphonesimulator ACTIVE_ARCH_ONLY=0
